notifications:
  email:
    on_success: never
    on_failure: change

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

sudo: false

git:
  depth: 10

branches:
  only:
    - master

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES=""
    - AUTHORIZED_BRANCH="master"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libsecret-1-dev
    - fakeroot

after_success:
  - ./.travis/publish.sh
